---
dns_state: present
dns_config_dir: "{{ config_root }}/dns"

dns_dnscrypt:
  image: klutchell/dnscrypt-proxy:2.1.15
  # auth
  username: "CHANGE-ME"
  password: "CHANGE-ME"
  # access
  port: 8302
  bind_ip: "172.19.1.100"

dns_pihole:
  image: pihole/pihole:2025.11.1
  # auth
  password: CHANGE-ME
  # access
  port: 8001
