---
- name: Install libicu74 for pg_search
  ansible.builtin.apt:
    name: libicu74
    state: present

- name: Install PostGIS
  ansible.builtin.apt:
    name: postgresql-{{ postgresql_major_version }}-postgis
    state: present
  notify: Restart PostgreSQL

- name: Install pgvector
  ansible.builtin.apt:
    name: postgresql-{{ postgresql_major_version }}-pgvector
    state: present
  notify: Restart PostgreSQL

- name: Install pg_search
  ansible.builtin.apt:
    deb: "https://github.com/paradedb/paradedb/releases/download/v{{ postgresql_extensions.pg_search.version }}/{{ filename }}"
  vars:
    filename: "postgresql-{{- postgresql_major_version -}}-pg-search_{{- postgresql_extensions.pg_search.version -}}\
              -1PARADEDB-{{- ansible_distribution_release -}}_{{ os_arch }}.deb"
  notify: Restart PostgreSQL

- name: Install VectorChord
  ansible.builtin.apt:
    deb: "https://github.com/tensorchord/VectorChord/releases/download/{{ postgresql_extensions.vectorchord.version }}/{{ filename }}"
  vars:
    filename: postgresql-{{ postgresql_major_version }}-vchord_{{ postgresql_extensions.vectorchord.version }}-1_{{ os_arch }}.deb
  notify: Restart PostgreSQL

- name: Enable pg_search and VectorChord
  community.postgresql.postgresql_set:
    name: shared_preload_libraries
    value: "pg_search, vchord"
  notify: Restart PostgreSQL
