---
- name: Restart Mikrotik MKTXP Exporter
  community.docker.docker_container:
    state: started
    restart: true
    name: exporter_mikrotik
    image: "{{ ritsu.components.exporter_mikrotik.image }}"
