---
# ------------------------------------------------------------------------------
# Plex
# Media server!!
ritsu:
  components:
    plex:
      # docker image to run
      image: linuxserver/plex:1.32.1

      # persistent dir
      # only one dir is needed, you can pick your libraries later
      media_dir: /media/primary/media

      # external access
      port: 8008

      # claim token
      claim_token: ""
