---
- name: Pull image from registry
  community.docker.docker_image:
    state: "{{ influxdb_state }}"
    name: "{{ influxdb_image }}"
    source: pull

- name: Start and connect container to network
  community.docker.docker_container:
    name: influxdb2
    image: "{{ influxdb_image }}"
    recreate: true
    user: "{{ docker_user.uid }}:{{ docker_user.gid }}"
    restart_policy: unless-stopped
    published_ports:
      - "{{ influxdb_port }}:8086"
    networks:
      - name: "{{ docker_network.name }}"
    env:
      DOCKER_INFLUXDB_INIT_MODE: "{{ influxdb_init.mode }}"
      DOCKER_INFLUXDB_INIT_USERNAME: "{{ influxdb_init.username }}"
      DOCKER_INFLUXDB_INIT_PASSWORD: "{{ influxdb_init.password }}"
      DOCKER_INFLUXDB_INIT_ORG: "{{ influxdb_init.organization }}"
      DOCKER_INFLUXDB_INIT_BUCKET: "{{ influxdb_init.bucket }}"
    volumes:
      - "{{ config_dir }}/influxdb/data:/var/lib/influxdb2:rw"
      - "{{ config_dir }}/influxdb/config:/etc/influxdb2:rw"
    state: "{{ 'started' if (influxdb_state == 'present') else 'absent' }}"
