---
- name: Create config directory
  ansible.builtin.file:
    path: "{{ config_dir }}/influxdb/{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "config"
    - "data"

- name: Install InfluxDB 2.0
  ansible.builtin.import_tasks: install-influxdb2.yml

- name: Install Telegraf
  ansible.builtin.import_tasks: install-telegraf.yml
