---
- name: Create Grafana directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
  loop:
    - "{{ ritsu.config_dir }}/grafana/data"
    - "{{ ritsu.config_dir }}/grafana/import_dashboards"
    - "{{ ritsu.config_dir }}/grafana/provisioning/dashboards"
    - "{{ ritsu.config_dir }}/grafana/provisioning/datasources"

- name: Provision data sources
  ansible.builtin.import_tasks: provision_datasource.yml

- name: Provision dashboards
  ansible.builtin.import_tasks: provision_dashboards.yml
