---
- name: Check if data directory is exists
  ansible.builtin.stat:
    path: "{{ data_dir }}/grafana"
  register: grafana_data_dir_stat

- name: Create data directory
  ansible.builtin.file:
    path: "{{ data_dir }}/grafana"
    state: directory
    mode: '0755'
  when: grafana_data_dir_stat.stat.exists == false

- name: Check if config directory is exists
  ansible.builtin.stat:
    path: "{{ config_dir }}/grafana/provisioning/datasources"
  register: grafana_config_dir_stat

- name: Create config directory
  ansible.builtin.file:
    path: "{{ config_dir }}/grafana/provisioning/datasources"
    state: directory
    mode: '0755'
  when: grafana_config_dir_stat.stat.exists == false

- name: Generate config files
  ansible.builtin.template:
    src: templates/{{ item.src }}
    dest: "{{ config_dir }}/grafana/{{ item.dest }}"
    mode: 0644
  loop:
    - src: provisioning/datasources.yml.j2
      dest: provisioning/datasources/datasource.yml
