---
- name: Pull Grafana image from Docker Hub
  community.docker.docker_image:
    name: "{{ grafana.image }}"
    source: pull

- name: Start and connect container to main network (with Grafana provisioning)
  community.docker.docker_container:
    name: grafana
    image: "{{ grafana.image }}"
    state: started
    restart: true
    restart_policy: always
    exposed_ports:
      - "3000:3000"
    published_ports:
      - "{{ grafana.port }}:3000"
    networks:
      - name: mainnet
    env:
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana.password }}"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_INSTALL_PLUGINS: flant-statusmap-panel,ae3e-plotly-panel
    volumes:
      - "{{ data_dir }}/grafana:/var/lib/grafana"
      - "{{ config_dir }}/grafana/provisioning/:/etc/grafana/provisioning/:ro"
