---
- name: Create Grafana directories
  ansible.builtin.file:
    path: "{{ config_dir }}/grafana/{{ item }}"
    state: directory
    mode: "0777"
  loop:
    - "data"
    - "import_dashboards"
    - "provisioning/dashboards"
    - "provisioning/datasources"

- name: Provision data sources
  ansible.builtin.import_tasks: provision-datasource.yml

- name: Provision dashboards
  ansible.builtin.import_tasks: provision-dashboards.yml

- name: Pull image from registry
  community.docker.docker_image:
    state: "{{ grafana_state }}"
    name: "{{ grafana_image }}"
    source: pull

- name: Start and connect container to network
  community.docker.docker_container:
    name: grafana
    image: "{{ grafana_image }}"
    user: "{{ docker_user.uid }}:{{ docker_user.gid }}"
    restart_policy: unless-stopped
    published_ports:
      - "{{ grafana_port }}:3000"
    networks:
      - name: "{{ docker_network.name }}"
    env:
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_password }}"
      GF_USERS_ALLOW_SIGN_UP: "{{ grafana_allow_signup | string | lower }}"
      GF_INSTALL_PLUGINS: "flant-statusmap-panel,ae3e-plotly-panel"
    volumes:
      - "{{ config_dir }}/grafana/data:/var/lib/grafana"
      - "{{ config_dir }}/grafana/provisioning/:/etc/grafana/provisioning/"
      - "{{ config_dir }}/grafana/import_dashboards:/var/lib/grafana/dashboards"
    labels:
      - flame.type=application
      - flame.name=Grafana
      - flame.url=http://{{ flame_hostname }}:{{ grafana_port }}
      - flame.icon=custom
    state: "{{ 'started' if (grafana_state == 'present') else 'absent' }}"
