---
- name: Generate data source provisioning config
  ansible.builtin.template:
    src: templates/{{ item.src }}
    dest: "{{ ritsu.config_dir }}/grafana/provisioning/{{ item.dest }}"
    mode: "0777"
  notify: restart_grafana
  when: ritsu.components.prometheus.enabled
  loop:
    - src: provision_datasource.yml.j2
      dest: datasources/default.yml
