---
- name: Generate data source provisioning config
  ansible.builtin.template:
    src: templates/{{ item.src }}
    dest: "{{ config_dir }}/grafana/provisioning/{{ item.dest }}"
    mode: "0775"
  notify: Restart Grafana
  when: prometheus_state == 'present'
  loop:
    - src: provision_datasource.yml.j2
      dest: datasources/default.yml
