---
- name: Pull image from registry
  community.docker.docker_image:
    state: "{{ ritsu.components.jellyfin.state }}"
    name: "{{ ritsu.components.jellyfin.image }}"
    source: pull

- name: Start and connect container to network
  community.docker.docker_container:
    state: "{{ 'started' if (ritsu.components.jellyfin.state == 'present') else 'absent' }}"
    image: "{{ ritsu.components.jellyfin.image }}"
    name: jellyfin
    restart_policy: unless-stopped
    published_ports:
      - "{{ ritsu.components.jellyfin.port }}:8096"
    networks:
      - name: "{{ ritsu.network.name }}"
    volumes:
      - "{{ ritsu.config_dir }}/jellyfin/config:/config:rw"
      - "{{ ritsu.config_dir }}/jellyfin/cache:/cache:rw"
    mounts:
      - source: "{{ ritsu.components.jellyfin.media_dir }}"
        target: /media
        type: bind
        read_only: false
