---
- name: Create config directories
  ansible.builtin.file:
    path: "{{ jellyfin_config_dir }}/{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "config"
    - "cache"

- name: Check if media directory is exists
  ansible.builtin.stat:
    path: "{{ jellyfin_media_dir }}"
  register: jellyfin_media_dir_exists

- name: Assert media directory exists
  ansible.builtin.assert:
    that:
      - jellyfin_media_dir_exists.stat.exists
      - jellyfin_media_dir_exists.stat.isdir

- name: Pull image from registry
  community.docker.docker_image:
    state: "{{ jellyfin_state }}"
    name: "{{ jellyfin_image }}"
    source: pull

- name: Start and connect container to network
  community.docker.docker_container:
    name: jellyfin
    image: "{{ jellyfin_image }}"
    restart_policy: unless-stopped
    published_ports:
      - "{{ jellyfin_port }}:8096"
    networks:
      - name: ritsu-pi
    volumes:
      - "{{ jellyfin_config_dir }}/config:/config:rw"
      - "{{ jellyfin_config_dir }}/cache:/cache:rw"
      - "{{ jellyfin_media_dir }}:/media:rw"
    devices:
      - "/dev/dri:/dev/dri"
    labels:
      flame.type: "application"
      flame.name: "Jellyfin"
      flame.url: "http://{{ server_hostname }}:{{ jellyfin_port }}"
      flame.icon: "custom"
    state: "{{ 'started' if jellyfin_state == 'present' else 'absent' }}"
