---
profile: safety

use_default_rules: true
enable_list:
  - args
  - empty-string-compare
  - no-log-password
  - no-same-owner
  - name[casing]
  - name[missing]
  - name[play]

# skip_list:

warn_list:
  - package-latest
  - command-instead-of-module
  - yaml[line-length]

exclude_paths:
  - .github
  - .vscode
