---
# Global config for Ritsu-Pi.
# To see the list of available components and it's configurations, see the "roles" directory
ritsu:
  # Location where configuration files be stored.
  # Note: Avoid the use of relative path!
  config_dir: '/media/primary/ritsu-pi/config'

  # Feature toggle
  components:
    # monitoring tools
    cadvisor:
      enabled: true

    prometheus:
      enabled: true

    grafana:
      enabled: true

    exporter_node:
      enabled: true

    exporter_blackbox:
      enabled: true

    # MKTXP Mikrotik Exporter
    exporter_mikrotik:
      enabled: true
      router_hostname: 10.20.20.1
      router_api_port: 8728
      router_username: admin
      router_password: admin

    exporter_speedtest:
      enabled: true

    # ----- networking tools
    dnscrypt:
      enabled: true

    pihole:
      enabled: true

    reverse_proxy:
      enabled: true
      domain: ramiel.local

    # ----- downloaders
    jdownloader:
      enabled: true

      device: RAMIEL-PI
      email: "fahminlb33@gmail.com"
      password: "meong"

    qbittorrent:
      enabled: true

    # ----- media server
    samba:
      enabled: true
      # user to access the network share
      user:
        username: ramiel
        password: meong

      # directory to share to samba
      mount_points:
        - name: ramiel_primary
          path: /media/primary
          writeable: true
          create_mask: "0777"
          directory_mask: "0777"
          public: false

    jellyfin:
      enabled: true
