---
# Location where configuration files will be stored.
# Note: Vaoid the use of relative path!
config_dir: '/media/primary/ritsu-pi-config'
data_dir: '/media/primary/ritsu-pi-data'

# Global home domain (when you're using pi-hole)
global_domain: ramiel.local

# Feature toggle
ritsu_components:
  # networking tools
  dnscrypt: true
  pihole: true
  reverse_proxy: true

  # monitoring tools
  prometheus: false
  grafana: false
  cadvisor: false
  exporter_node: false
  exporter_blackbox: false
  exporter_mikrotik: false
  exporter_speedtest: false

  # downloaders
  jdownloader: false
  qbittorrent: false

  # media server
  samba: false
  jellyfin: false

# MyJDownloader
myjdownloader:
  device: RAMIEL-PI
  email: "fahminlb33@gmail.com"
  password: "meong"

# MKTXP Mikrotik Exporter
mktxp:
  router_hostname: 10.20.20.1
  router_api_port: 8728
  router_username: admin
  router_password: admin

# Samba Network Share
samba:
  # user to access the network share
  user:
    username: ramiel
    password: meong

  # directory to share to samba
  mount_points:
    - name: ramiel_primary
      path: /media/primary
      writeable: true
      create_mask: 0777
      directory_mask: 0777
      public: false
