---
- name: Ritsu-pi Project
  hosts: ritsu_pi
  tasks:
    - name: Install basic packages
      ansible.builtin.import_tasks: tasks/base.yml

    - name: Install Docker
      ansible.builtin.import_tasks: tasks/docker.yml

- name: Networking
  ansible.builtin.import_playbook: play_networking.yml

- name: Monitoring
  ansible.builtin.import_playbook: play_monitoring.yml

- name: Multimedia
  ansible.builtin.import_playbook: play_multimedia.yml

- name: Developer Tools
  ansible.builtin.import_playbook: play_devtools.yml

- name: Reverse Proxy
  ansible.builtin.import_playbook: play_reverse-proxy.yml
