---
- name: Ritsu-pi Project
  hosts: ritsu_pi
  pre_tasks:
    - name: Load configuration
      ansible.builtin.include_vars:
        file: config.example.yml
    - name: Debugggg
      debug:
        var: vars

  roles:
    # common
    - role: common
      tags: [common]
    - role: docker
      tags: [common, docker]

    # networking
    - role: dnscrypt
      tags: [dnscrypt]
      when: ritsu_components.dnscrypt == true
    - role: pihole
      tags: [pihole]
      when: ritsu_components.pihole == true
    - role: reverse_proxy
      tags: [nginx]
      when: ritsu_components.reverse_proxy == true

    # monitoring
    - role: prometheus
      tags: [prometheus]
      when: ritsu_components.prometheus == true
    - role: grafana
      tags: [grafana]
      when: ritsu_components.grafana == true
    - role: cadvisor
      tags: [cadvisor]
      when: ritsu_components.cadvisor == true
    - role: exporter_node
      tags: [exporter_node]
      when: ritsu_components.exporter_node == true
    - role: exporter_blackbox
      tags: [exporter_blackbox]
      when: ritsu_components.exporter_blackbox == true
    - role: exporter_mikrotik
      tags: [mikrotik]
      when: ritsu_components.exporter_mikrotik == true
    - role: exporter_speedtest
      tags: [exporter_speedtest]
      when: ritsu_components.exporter_speedtest == true

    # downloaders
    - role: jdownloader
      tags: [jdownloader]
      when: ritsu_components.jdownloader == true
    - role: qbittorrent
      tags: [qbittorrent]
      when: ritsu_components.qbittorrent == true

    # media server
    - role: samba
      tags: [samba]
      when: ritsu_components.samba == true
    - role: jellyfin
      tags: [jellyfin]
      when: ritsu_components.jellyfin == true
