---
- name: Ritsu-pi Project
  hosts: ritsu_pi
  pre_tasks:
    - name: Load configuration
      ansible.builtin.include_vars:
        file: config.yml

  roles:
    # common
    - role: common
      tags: [common]
    - role: docker
      tags: [common, docker]

    # networking
    - role: dnscrypt
      tags: [dnscrypt]
      when: ritsu.components.dnscrypt.enabled == true
    - role: pihole
      tags: [pihole]
      when: ritsu.components.pihole.enabled == true
    - role: reverse_proxy
      tags: [nginx]
      when: ritsu.components.reverse_proxy.enabled == true

    # monitoring
    - role: prometheus
      tags: [prometheus]
      when: ritsu.components.prometheus.enabled == true
    - role: grafana
      tags: [grafana]
      when: ritsu.components.grafana.enabled == true
    - role: cadvisor
      tags: [cadvisor]
      when: ritsu.components.cadvisor.enabled == true
    - role: exporter_node
      tags: [exporter_node]
      when: ritsu.components.exporter_node.enabled == true
    - role: exporter_blackbox
      tags: [exporter_blackbox]
      when: ritsu.components.exporter_blackbox.enabled == true
    - role: exporter_mikrotik
      tags: [mikrotik]
      when: ritsu.components.exporter_mikrotik.enabled == true
    - role: exporter_speedtest
      tags: [exporter_speedtest]
      when: ritsu.components.exporter_speedtest.enabled == true
    - role: exporter_sensor_suhu_server
      tags: [exporter_sensor_suhu_server]
      when: ritsu.components.exporter_sensor_suhu_server.enabled == true

    # downloaders
    - role: jdownloader
      tags: [jdownloader]
      when: ritsu.components.jdownloader.enabled == true
    - role: qbittorrent
      tags: [qbittorrent]
      when: ritsu.components.qbittorrent.enabled == true

    # media server
    - role: samba
      tags: [samba]
      when: ritsu.components.samba.enabled == true
    - role: jellyfin
      tags: [jellyfin]
      when: ritsu.components.jellyfin.enabled == true
