- name: Ritsu-pi Project
  hosts: ritsu_pi
  pre_tasks:
    - name: Load configuration
      ansible.builtin.include_vars:
      loop:
        - config.example.yml
        - config.yml
  roles:
    - role: common
    - role: docker
      tags: [docker]
  tags: [common]

- name: Networking
  hosts: ritsu_pi
  roles:
    - role: dnscrypt
      tags: [dnscrypt]
      when: features.dnscrypt == true
    - role: pihole
      tags: [pihole]
      when: features.pihole == true
    - role: reverse_proxy
      tags: [nginx]
      when: features.reverse_proxy == true
  tags: [networking]

- name: Monitoring
  hosts: ritsu_pi
  roles:
    - role: prometheus
      tags: [prometheus]
      when: features.prometheus == true
    - role: grafana
      tags: [grafana]
      when: features.grafana == true
    - role: cadvisor
      tags: [cadvisor]
      when: features.cadvisor == true
    - role: exporter_node
      tags: [exporter_node]
      when: features.exporter_node == true
    - role: exporter_blackbox
      tags: [exporter_blackbox]
      when: features.exporter_blackbox == true
    - role: exporter_mikrotik
      tags: [mikrotik]
      when: features.exporter_mikrotik == true
    - role: exporter_speedtest
      tags: [exporter_speedtest]
      when: features.exporter_speedtest == true
  tags: [monitoring]

- name: Downloaders
  hosts: ritsu_pi
  roles:
    - role: jdownloader
      tags: [jdownloader]
      when: features.jdownloader == true
    - role: qbittorrent
      tags: [qbittorrent]
      when: features.qbittorrent == true
  tags: [downloaders]

- name: Media Server
  hosts: ritsu_pi
  roles:
    - role: samba
      tags: [samba]
      when: features.samba == true
  tags: [media_server]
