---
- name: Create config directory
  ansible.builtin.file:
    path: "{{ config_dir }}/flame"
    state: directory
    mode: "0775"
  register: flame_config_dir

- name: Pull image from registry
  community.docker.docker_image:
    state: "{{ flame_state }}"
    name: "{{ flame_image }}"
    source: pull

- name: Start and connect container to network
  community.docker.docker_container:
    name: flame
    image: "{{ flame_image }}"
    recreate: true
    # user: "{{ docker_user.uid }}:{{ docker_user.gid }}"
    restart_policy: unless-stopped
    published_ports:
      - "80:5005"
    networks:
      - name: "{{ docker_network.name }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "{{ flame_config_dir.path }}:/app/data:rw"
    env:
      PASSWORD: "{{ flame_password }}"
    state: "{{ 'started' if (flame_state == 'present') else 'absent' }}"
