---
# Prometheus Node Exporter
#
# Note:
# Node exporter will be installed in your pi, not in Docker.
ritsu:
  components:
    exporter_node:
      version: 1.7.0
      arch: linux-armv7
      install_path: /usr/local/bin/node_exporter

      # web UI access
      port: 8104
