---
- name: Set OS architecture fact
  ansible.builtin.set_fact:
    os_arch: "{{ [ansible_architecture] | map('extract', deb_arch) | first }}"
  vars:
    deb_arch:
      x86_64: amd64
      aarch64: arm64
      armv7l: armhf

- name: Create configuration root directory
  ansible.builtin.file:
    path: "{{ config_root }}"
    state: directory
    mode: "0775"

- name: Install required system packages # noqa: package-latest
  ansible.builtin.apt:
    name:
      - jq
      - git
      - curl
      - ca-certificates
      - apt-transport-https
      - software-properties-common
      - libffi-dev
      - libssl-dev
      - python3-dev
      - python3-pip
      - smartmontools
    update_cache: true
    state: present
  become: true

- name: Install Docker
  ansible.builtin.import_tasks: docker.yml
