---
nginx_state: present
nginx_cloudflare_token: <TOKEN HERE>
nginx_apex_domain: ritsu.net
nginx_ip: 10.20.20.101
nginx_cockpit_vhost: cockpit.ritsu.net
nginx_vhosts:
  - hostname: www.testing.com
    upstream: docker-host:port
