---
# Prometheus Blackbox Exporter
#
# Note:
# This template only comes with minimal HTTP 2xx check. If you want to add more
# checks, edit the template in the templates/config.yml.j2
# Doc: https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md
ritsu:
  components:
    exporter_blackbox:
      image: prom/blackbox-exporter:v0.23.0

      # web UI access
      port: 8102

      # hosts to ping
      ping_hosts:
        - https://www.google.com/
        - https://github.com/
