---
# ------------------------------------------------------------------------------
# Prometheus Blackbox Exporter
# The blackbox exporter allows blackbox probing of endpoints over HTTP, HTTPS,
# DNS, TCP, ICMP and gRPC.
#
# Depends on:
# - prometheus
#   Uses prometheus to collect metrics.
#   If prometheus is disabled, the play will fail.
# - grafana
#   If grafana is enabled, a dashboard will be provisioned.
#
# Note:
# This template only comes with minimal HTTP 2xx check. If you want to add more
# checks, edit the template in the templates/config.yml.j2
# Doc: https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md
ritsu:
  components:
    exporter_blackbox:
      # docker image to run
      image: prom/blackbox-exporter:latest

      # access port
      port: 8102

      # hosts to ping
      ping_hosts:
        - https://www.google.com/
        - https://github.com/

      # when using reverse proxy, http://{{subdomain}}.{{global_domain}}
      subdomain: blackbox
