---
- name: Pull image from registry
  community.docker.docker_image:
    name: "{{ ritsu.components.exporter_cadvisor.image }}"
    source: pull

- name: Start and connect container to network
  community.docker.docker_container:
    state: started
    name: exporter_cadvisor
    image: "{{ ritsu.components.exporter_cadvisor.image }}"
    restart: true
    restart_policy: unless-stopped
    privileged: true
    exposed_ports:
      - 8080:8080
    published_ports:
      - "{{ ritsu.components.exporter_cadvisor.port }}:8080"
    networks:
      - name: "{{ ritsu.network.name }}"
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/run:/var/run:rw
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
