- name: Configure Blackbox exporter
  ansible.builtin.import_tasks: blackbox.yml
  when: monitoring_exporters.blackbox.state == "present"

- name: Configure Mikrotik exporter
  ansible.builtin.import_tasks: mikrotik.yml
  when: monitoring_exporters.mikrotik.state == "present"
