{
 "title": "APC UPS",
 "description": "Dashboard for apcupsd_exporter",
 "tags": [ "apcupsd" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ups", "label": "UPS", "query": { "query": "label_values(apcupsd_info,ups)" } }
  ]
 },
 "panels": [
  {
   "title": "UPS List",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(apcupsd_info) by (ups, instance, job, model, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "$ups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "ups" },
  {
   "title": "Load Percentage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apcupsd_ups_load_percent{ups=\"$ups\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apcupsd_nominal_power_watts{ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apcupsd_battery_charge_percent{ups=\"$ups\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery Time Left",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apcupsd_battery_time_left_seconds{ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "Time On Battery",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apcupsd_battery_time_on_seconds{ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "Cumulative Time On Battery",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apcupsd_battery_cumulative_time_on_seconds_total"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "apcupsd_nominal_power_watts{ups=\"$ups\"}",
     "legendFormat": "Watts"
    },
    {
     "expr": "apcupsd_ups_load_percent{ups=\"$ups\"}",
     "legendFormat": "Percentage"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "apcupsd_battery_charge_percent{ups=\"$ups\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AC Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "apcupsd_line_volts{ups=\"$ups\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery Time Left",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "apcupsd_battery_time_left_seconds{ups=\"$ups\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time On Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "apcupsd_battery_time_on_seconds{ups=\"$ups\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "apcupsd_battery_volts{ups=\"$ups\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}