{
 "title": "Internet Uptime",
 "tags": [
  "blackbox",
  "internet",
  "latency",
  "prometheus",
  "network"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Github Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://github.com/\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Github Avg. Req. Duration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{instance=\"https://github.com/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Github Max. Req. Duration",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{instance=\"https://github.com/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Google Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://github.com/\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Google Avg. Req. Duration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{instance=\"https://www.google.com/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Google Max. Req. Duration",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{instance=\"https://www.google.com/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Github Min. Req. Duration",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{instance=\"https://github.com/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Google Min. Req. Duration",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{instance=\"https://www.google.com/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Github Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{instance=\"https://github.com/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Google Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{instance=\"https://www.google.com/\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}