{
 "title": "Server Temperature & Humidity",
 "tags": [
  "server",
  "hardware",
  "temperature",
  "humidity",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "humididy{source=\"kodesiana_iot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{source=\"kodesiana_iot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heat Index",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "heat_index{source=\"kodesiana_iot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "humididy{source=\"kodesiana_iot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "temperature{source=\"kodesiana_iot\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heat Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "heat_index{source=\"kodesiana_iot\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}