{
 "title": "Speedtest",
 "description": "Speedtest metrics",
 "tags": [
  "networking",
  "speedtest"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ISP",
    "label": "ISP",
    "query": {
     "query": "label_values(speedtest_ping_latency_milliseconds,isp)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg(speedtest_download_bandwidth_bits_per_second{isp=~\"$ISP\"})",
     "legendFormat": "Download"
    },
    {
     "expr": "avg(speedtest_upload_bandwidth_bits_per_second{isp=~\"$ISP\"})",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(speedtest_download_bandwidth_bits_per_second{isp=~\"$ISP\"}[1w:5m]))",
     "legendFormat": "Best"
    },
    {
     "expr": "min(min_over_time(speedtest_download_bandwidth_bits_per_second{isp=~\"$ISP\"}[1w:5m]))",
     "legendFormat": "Worst"
    },
    {
     "expr": "avg(avg_over_time(speedtest_download_bandwidth_bits_per_second[1w:5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(speedtest_upload_bandwidth_bits_per_second{isp=~\"$ISP\"}[1w:5m]))",
     "legendFormat": "Best"
    },
    {
     "expr": "min(min_over_time(speedtest_upload_bandwidth_bits_per_second{isp=~\"$ISP\"}[1w:5m]))",
     "legendFormat": "Worst"
    },
    {
     "expr": "avg(avg_over_time(speedtest_upload_bandwidth_bits_per_second[1w:5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(speedtest_ping_latency_milliseconds{isp=~\"$ISP\"}[1w:5m]))",
     "legendFormat": "Best"
    },
    {
     "expr": "max(max_over_time(speedtest_ping_latency_milliseconds{isp=~\"$ISP\"}[1w:5m]))",
     "legendFormat": "Worst"
    },
    {
     "expr": "avg(avg_over_time(speedtest_ping_latency_milliseconds[1w:5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Ping Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(speedtest_ping_latency_milliseconds)",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(speedtest_upload_latency_milliseconds)",
     "legendFormat": "Upload"
    },
    {
     "expr": "avg(speedtest_download_latency_milliseconds)",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "Test Results",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "speedtest_download_bandwidth_bits_per_second"
    },
    {
     "expr": "speedtest_upload_bandwidth_bits_per_second"
    },
    {
     "expr": "speedtest_ping_latency_milliseconds",
     "legendFormat": "Latency"
    },
    { "expr": "speedtest_upload_size_bytes", "legendFormat": "Uploaded" },
    { "expr": "speedtest_download_size_bytes", "legendFormat": "Downloaded" }
   ]
  }
 ]
}