---
- name: Create Ollama config directory
  ansible.builtin.file:
    path: "{{ ollama_config_dir }}/{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "ollama-cache"
    - "open-webui"

- name: Pull image from registry
  community.docker.docker_image:
    state: "{{ ollama_state }}"
    name: "{{ item }}"
    source: pull
  loop:
    - "{{ ollama_image }}"
    - "{{ ollama_open_webui_image }}"

- name: Copy Docker Compose template
  ansible.builtin.template:
    src: templates/compose.yml.j2
    dest: "{{ ollama_config_dir }}/compose.yml"
    mode: "0775"

- name: Start Docker Compose services
  community.docker.docker_compose_v2:
    state: "{{ ollama_state }}"
    project_src: "{{ ollama_config_dir }}"
