---
# ------------------------------------------------------------------------------
# qBittorrent
# The best bittorrent client.
# You can access the download queue from the web interface.
ritsu:
  components:
    qbittorrent:
      # image
      image: lscr.io/linuxserver/qbittorrent:latest

      # web UI
      port: 8006

      # download directory
      download_dir: /media/primary/downloads

      # extra arguments
      tz: Asia/Jakarta
