---
# qBittorrent
qbittorrent_state: present
qbittorrent_image: lscr.io/linuxserver/qbittorrent:4.6.7

# web UI access
qbittorrent_port: 8006

# download directory
qbittorrent_download_dir: /media/primary/downloads

# use gluetun?
qbittorrent_gluetun: false
