---
# qBittorrent
ritsu:
  components:
    qbittorrent:
      state: present
      image: lscr.io/linuxserver/qbittorrent:4.6.1

      # web UI access
      port: 8006

      # download directory
      download_dir: /media/primary/downloads
