---
- name: Create config directory
  ansible.builtin.file:
    path: "{{ ritsu.config_dir }}/exporter_blackbox"
    state: directory
    mode: 0775
  register: config_output

- name: Create configuration
  ansible.builtin.template:
    src: templates/config.yml.j2
    dest: "{{ config_output.path }}/blackbox.yml"
    mode: 0775
  notify: restart_exporter_blackbox
