---
- name: Pull image from registry
  community.docker.docker_image:
    state: "{{ ritsu.components.exporter_blackbox.state }}"
    name: "{{ ritsu.components.exporter_blackbox.image }}"
    source: pull

- name: Start and connect container to network
  community.docker.docker_container:
    state: "{{ 'started' if (ritsu.components.exporter_blackbox.state == 'present') else 'absent' }}"
    image: "{{ ritsu.components.exporter_blackbox.image }}"
    name: exporter_blackbox
    restart_policy: unless-stopped
    command:
      - --config.file=/config/blackbox.yml
    exposed_ports:
      - 9115:9115
    published_ports:
      - "{{ ritsu.components.exporter_blackbox.port }}:9115"
    networks:
      - name: "{{ ritsu.network.name }}"
    volumes:
      - "{{ ritsu.config_dir }}/exporter_blackbox/blackbox.yml:/config/blackbox.yml:ro"
