---
- name: Pull image from registry
  community.docker.docker_image:
    state: "{{ ritsu.components.qbittorrent.state }}"
    name: "{{ ritsu.components.qbittorrent.image }}"
    source: pull

- name: Start and connect container to network
  community.docker.docker_container:
    state: "{{ 'started' if (ritsu.components.qbittorrent.state == 'present') else 'absent' }}"
    image: "{{ ritsu.components.qbittorrent.image }}"
    name: qbittorrent
    restart_policy: unless-stopped
    env:
      TZ: "{{ ritsu.timezone }}"
      WEBUI_PORT: "{{ ritsu.components.qbittorrent.port }}"
    published_ports:
      - 6881:6881
      - 6881:6881/udp
      - "{{ ritsu.components.qbittorrent.port }}:{{ ritsu.components.qbittorrent.port }}"
    networks:
      - name: "{{ ritsu.network.name }}"
    volumes:
      - "{{ ritsu.config_dir }}/qbittorrent:/config:rw"
      - "{{ ritsu.components.qbittorrent.download_dir }}:/downloads:rw"
