---
- name: Ensure package is installed
  ansible.builtin.package:
    name: qbittorrent-nox
    state: "{{ qbittorrent_nox_package_state | default(present) }}"
  notify: restart service

- name: Ensure service user exists
  ansible.builtin.user:
    name: qbittorrent-nox
    comment: qBittorrent nox user
    shell: /usr/sbin/nologin
    system: true
    groups: qbittorrent-nox
    state: present
  register: qbittorrent_nox_user_info

- name: Ensure config directory exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
    owner: "{{ qbittorrent_nox_user_info.name }}"
    group: "{{ qbittorrent_nox_user_info.group }}"
  with_items:
    - "{{ qbittorrent.config_dir }}/.config/"
    - "{{ qbittorrent.config_dir }}/.config/qBittorrent/"

- name: Ensure legal notice is accepted
  ansible.builtin.lineinfile:
    path: "{{ qbittorrent.config_dir }}/.config/qBittorrent/qBittorrent.conf"
    regexp: "{{ item.re }}"
    line: "{{ item.line }}"
    insertafter: "{{ item.after | default(omit) }}"
    create: true
    owner: "{{ qbittorrent_nox_user_info.name }}"
    group: "{{ qbittorrent_nox_user_info.group }}"
    mode: 0644
  with_items:
    - re: '^\[LegalNotice\]$'
      line: "[LegalNotice]"
    - re: "^Accepted=true$"
      line: "Accepted=true"
      after: '^\[LegalNotice\]$'
    - re: '^\[BitTorrent\]$'
      line: "[BitTorrent]"
    - re: "^Session\\Port$"
      line: "Session\\Port={{ qbittorrent.ports.torrent }}"
      after: '^\[BitTorrent\]$'
    - re: '^\[Network\]$'
      line: "[Network]"
    - re: "^PortForwardingEnabled$"
      line: "PortForwardingEnabled=false"
      after: '^\[Network\]$'

- name: Ensure systemd unit file is present
  ansible.builtin.template:
    src: qbittorrent-nox.service.j2
    dest: /etc/systemd/system/qbittorrent-nox.service
    owner: root
    group: root
    mode: 0644
  become: true
  notify: restart_qbittorrent

- name: Ensure qBittorrent-nox is started
  ansible.builtin.systemd:
    name: qbittorrent-nox
    state: started
    enabled: true
  become: true
