---
- name: Create config directory
  ansible.builtin.file:
    path: "{{ ritsu.config_dir }}/dnscrypt"
    state: directory
    mode: "0775"
  register: dnscrypt_config_dir

- name: Create configuration
  ansible.builtin.template:
    src: templates/dnscrypt.toml.j2
    dest: "{{ dnscrypt_config_dir.path }}/dnscrypt-proxy.toml"
    mode: "0775"
  notify: Restart DNSCrypt
