---
- name: Pull image from registry
  community.docker.docker_image:
    state: "{{ ritsu.components.dnscrypt.state }}"
    name: "{{ ritsu.components.dnscrypt.image }}"
    source: pull

- name: Start and connect container to network
  community.docker.docker_container:
    state: "{{ 'started' if (ritsu.components.dnscrypt.state == 'present') else 'absent' }}"
    image: "{{ ritsu.components.dnscrypt.image }}"
    name: dnscrypt
    restart_policy: unless-stopped
    published_ports:
      - "{{ ritsu.components.dnscrypt.bind_dns_port }}:5053/udp"
      - "{{ ritsu.components.dnscrypt.bind_dns_port }}:5053/tcp"
    networks:
      - name: "{{ ritsu.network.name }}"
        ipv4_address: "{{ ritsu.components.dnscrypt.bind_ip }}"
    volumes:
      - "{{ dnscrypt_config_dir.path }}/dnscrypt-proxy.toml:/dnscrypt-proxy.toml:ro"
