---
- name: Pull image from registry
  community.docker.docker_image:
    name: "{{ ritsu.components.dnscrypt.image }}"
    source: pull

- name: Start and connect container to network
  community.docker.docker_container:
    state: started
    name: dnscrypt
    image: "{{ ritsu.components.dnscrypt.image }}"
    restart: true
    restart_policy: unless-stopped
    exposed_ports:
      - "{{ ritsu.components.dnscrypt.dns_port }}:53/udp"
      - "{{ ritsu.components.dnscrypt.dns_port }}:53/tcp"
    published_ports:
      - "{{ ritsu.components.dnscrypt.dns_port }}:53/udp"
      - "{{ ritsu.components.dnscrypt.dns_port }}:53/tcp"
    networks:
      - name: "{{ ritsu.network.name }}"
    volumes:
      - "{{ ritsu.config_dir }}/dnscrypt/dnscrypt-proxy.toml:/dnscrypt-proxy.toml:ro"
