---
# DNSCrypt
#
# Note:
# This tool works best with pi-hole enabled too. You'll need to configure your
# system's DNS to use the DNSCrypt server.
# Edit the templates/dnscrypt.toml.j2 for more options.
ritsu:
  components:
    dnscrypt:
      image: klutchell/dnscrypt-proxy:v2.1.5

      # internal docker network config
      bind_ip: "172.18.1.100"
      bind_dns_port: 54

      # upstream DNS servers
      upstream_dns:
        - cloudflare
        - google
