---
# DNSCrypt
#
# Note:
# This tool works best with pi-hole enabled too. You'll need to configure your
# system's DNS to use the DNSCrypt server.
# Edit the templates/dnscrypt.toml.j2 for more options.
dnscrypt_state: present

# docker image
dnscrypt_image: klutchell/dnscrypt-proxy:v2.1.5

# internal docker network config
dnscrypt_bind_ip: "172.18.1.100"
dnscrypt_bind_dns_port: 54

# upstream DNS servers
dnscrypt_upstream_dns:
  - cloudflare
  - google
