---
# ------------------------------------------------------------------------------
# DNSCrypt
# DNSCrypt server to secure your DNS queries.
#
# Note:
# This tool works best with pi-hole enabled too. You'll need to configure your
# system's DNS to use the DNSCrypt server.
# Edit the templates/dnscrypt.toml.j2 for more options.
ritsu:
  components:
    dnscrypt:
      # image to run in Docker
      image: klutchell/dnscrypt-proxy:latest

      # configure DNScrypt servers
      dns_port: 5053
      dns_upstream: [cloudflare, google]
