---
- name: Configure static network using dhcpcd
  ansible.builtin.import_tasks: network-dhcpcd.yml
  become: true
  when:
    - ansible_facts.os_family == "Debian"
    - ansible_facts.distribution_major_version == "11"

- name: Configure static network using NetworkManager
  ansible.builtin.import_tasks: network-nmcli.yml
  become: true
  when:
    - ansible_facts.os_family == "Debian"
    - ansible_facts.distribution_major_version == "12"
