---
- name: Install package
  ansible.builtin.apt:
    name: dhcpcd5
    state: present

- name: Create service configuration
  ansible.builtin.template:
    src: dhcpcd.conf.j2
    dest: /etc/dhcpcd.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart dhcpcd

- name: Enable service
  ansible.builtin.systemd:
    name: dhcpcd
    enabled: true
    daemon_reload: true

- name: Start service
  ansible.builtin.systemd:
    name: dhcpcd
    state: started
    daemon_reload: true
