---
- name: Install needed network manager libs
  ansible.builtin.package:
    name:
      - NetworkManager-libnm
      - nm-connection-editor
      - libsemanage-python
      - policycoreutils-python
    state: present

- name: Contfigure Ethernet connection with static IP
  community.general.nmcli:
    conn_name: ethernet
    ifname: eth0
    type: ethernet
    ip4: "{{ setup_network_ip_address }}"
    gw4: "{{ setup_network_gateway }}"
    dns4:
      - "{{ setup_network_dns_server }}"
    state: present
  notify: Restart NetworkManager
