---
- name: Create data directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "{{ ritsu.config_dir }}/portainer/data"
    - "{{ ritsu.config_dir }}/portainer/ssl"
