---
- name: Pull image from registry
  community.docker.docker_image:
    state: "{{ ritsu.components.portainer.state }}"
    name: "{{ ritsu.components.portainer.image }}"
    source: pull

- name: Start and connect container to network
  community.docker.docker_container:
    state: "{{ 'started' if (ritsu.components.portainer.state == 'present') else 'absent' }}"
    image: "{{ ritsu.components.portainer.image }}"
    name: portainer
    command: --bind :9000 --http-enabled
    restart_policy: unless-stopped
    published_ports:
      - "{{ ritsu.components.portainer.port }}:9000"
    networks:
      - name: "{{ ritsu.network.name }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ ritsu.config_dir }}/portainer/data:/data"
