---
- name: Restart Blackbox Exporter
  community.docker.docker_container:
    state: started
    restart: true
    name: exporter_blackbox
    image: "{{ ritsu.components.exporter_blackbox.image }}"
