---
- name: Create JDownloader directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: 0775
  loop:
    - "{{ ritsu.config_dir }}/jdownloader"

- name: Create download directory
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: 0775
  loop:
    - "{{ ritsu.components.jdownloader.download_dir }}"

