---
- name: Create config directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "{{ ritsu.config_dir }}/jdownloader"

- name: Check if download directory is exists
  ansible.builtin.stat:
    path: "{{ ritsu.components.jdownloader.download_dir }}"
  register: jdownloader_dir_exists

- name: Assert download directory exists
  ansible.builtin.assert:
    that:
      - jdownloader_dir_exists.stat.exists
      - jdownloader_dir_exists.stat.isdir
