{
 "title": "Network SpeedTest",
 "description": "Dashboard for Speedtest Exporter https://github.com/MiguelNdeCarvalho/speedtest-exporter",
 "tags": [
  "internet",
  "speedtest",
  "prometheus",
  "network"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(speedtest_up, instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(speedtest_up, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status of the Speedtest-Exporter",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_up{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "ServerID (Last test done)",
   "type": "stat",
   "description": "ServerID of the last test done",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_server_id{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Gauges",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Download Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{instance=\"$instance\", job=\"$job\"}*10^-6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Upload Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second{instance=\"$instance\", job=\"$job\"}*10^-6"
    }
   ]
  },
  {
   "title": "Average Ping",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Average Jitter",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_jitter_latency_milliseconds{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Graphics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Download Speed (Mbits/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{instance=\"$instance\", job=\"$job\"}*10^-6",
     "legendFormat": "Download Speed (Mbits/s)"
    }
   ]
  },
  {
   "title": "Upload Speed (Mbits/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second{instance=\"$instance\", job=\"$job\"}*10^-6",
     "legendFormat": "Upload Speed (Mbits/s)"
    }
   ]
  },
  {
   "title": "Ping and Jitter (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Ping (ms)"
    },
    {
     "expr": "speedtest_jitter_latency_milliseconds{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Jitter (ms)"
    }
   ]
  }
 ]
}