---
# ------------------------------------------------------------------------------
# JDownloader 2
# All-in-one downloader app.
#
# Note:
# You'll need MyJDownloader account to access the download queue.
ritsu:
  components:
    jdownloader:
      state: present
      image: jlesage/jdownloader-2:v23.11.2

      # web UI access
      port: 8007

      # download directory
      download_dir: /media/primary/downloads

      # MyJDownloader
      myjdownloader:
        device: RAMIEL-PI
        email: fahminlb33@gmail.com
        password: 8BJmYg7m%z7g
