---
- name: Create config and data directory
  ansible.builtin.file:
    path: "{{ ritsu.config_dir }}/prometheus/{{ item }}"
    state: directory
    mode: 0777
  loop:
    - etc
    - data

- name: Generate config files
  ansible.builtin.template:
    src: templates/prometheus.yml.j2
    dest: "{{ ritsu.config_dir }}/prometheus/etc/prometheus.yml"
    mode: 0775
