---
- name: Create config and data directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0644
  loop:
    - "{{ prometheus.data_dir }}/prometheus"

- name: Generate config files
  ansible.builtin.template:
    src: templates/{{ item.src }}
    dest: "{{ config_dir }}/prometheus/{{ item.dest }}"
    mode: 0644
  loop:
    - src: prometheus.yml.j2
      dest: prometheus.yml
