---
- name: Pull image from registry
  community.docker.docker_image:
    state: "{{ ritsu.components.prometheus.state }}"
    name: "{{ ritsu.components.prometheus.image }}"
    source: pull

- name: Start and connect container to network
  community.docker.docker_container:
    state: "{{ 'started' if (ritsu.components.prometheus.state == 'present') else 'absent' }}"
    image: "{{ ritsu.components.prometheus.image }}"
    name: prometheus
    restart_policy: unless-stopped
    user: root # sometimes prometheus can't write to data directory
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.size=100GB
      - --storage.tsdb.retention.time=180d
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    published_ports:
      - "{{ ritsu.components.prometheus.port }}:9090"
    networks:
      - name: "{{ ritsu.network.name }}"
    volumes:
      - "{{ ritsu.config_dir }}/prometheus/etc:/etc/prometheus/:rw"
      - "{{ ritsu.config_dir }}/prometheus/data:/prometheus/:rw"
