---
- name: Pull image from Docker Hub
  community.docker.docker_image:
    name: "{{ prometheus.image }}"
    source: pull

- name: Start and connect container to main network
  community.docker.docker_container:
    name: prometheus
    image: "{{ prometheus.image }}"
    restart: true
    state: started
    restart_policy: always
    hostname: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=90d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    exposed_ports:
      - "{{ prometheus.port }}:9090"
    published_ports:
      - "{{ prometheus.port }}:9090"
    networks:
      - name: mainnet
    volumes:
      - "{{ config_dir }}/prometheus/:/etc/prometheus/:ro"
      - "{{ data_dir }}/prometheus:/prometheus"
