---
- name: Install Node Exporter
  ansible.builtin.import_tasks: exporter-node.yml
  when: prometheus_exporters.node.enabled

- name: Install Blackbox Exporter
  ansible.builtin.import_tasks: exporter-blackbox.yml
  when: prometheus_exporters.blackbox.enabled

- name: Install cAdvisor Exporter
  ansible.builtin.import_tasks: exporter-cadvisor.yml
  when: prometheus_exporters.cadvisor.enabled

- name: Install Mikrotik Exporter
  ansible.builtin.import_tasks: exporter-mikrotik.yml
  when: prometheus_exporters.mikrotik.enabled

- name: Install Speedtest Exporter
  ansible.builtin.import_tasks: exporter-speedtest.yml
  when: prometheus_exporters.speedtest.enabled

- name: Install Prometheus
  ansible.builtin.import_tasks: install-prometheus.yml
