---
# ------------------------------------------------------------------------------
# Grafana
# Used to display metrics in a web interface.
#
# Depends on:
# - prometheus
#   Uses prometheus as data source.
#
# Note:
# Yes you can run Grafana without prometheus. But you will not be able to display
# any metrics. If you want a standalone Grafana instance, you can set the
# `standaonle` option to true.
grafana:
  # docker image to run
  image: grafana/grafana:8.2.6

  # external access
  port: 3000

  # if reverse-proxy is enabled, you can access this from a domain
  # http://grafana.{{global_domain}}
  standalone: false

  # login info
  password: 'admin'
  allow_signup: false

  # provisioning
  provisioning:
    # dashboards
    dashboards:
      - kind: import
        id: 13679 # mikrotik exporter
