---
# ------------------------------------------------------------------------------
# Grafana
# Used to display metrics in a web interface.
#
# Depends on:
# - prometheus
#   Uses prometheus as data source.
#
# Note:
# Yes you can run Grafana without prometheus. But you will not be able to display
# any metrics. If you want a standalone Grafana instance, you can set the
# `standaonle` option to true.
ritsu:
  components:
    grafana:
      # docker image to run
      image: grafana/grafana:8.2.6

      # external access
      port: 8001

      # when using reverse proxy, http://{{subdomain}}.{{global_domain}}
      subdomain: grafana

      # login info
      password: admin
      allow_signup: false

      # dashboard to provision from Grafana Cloud
      dashboard_provisioning:
        - id: 1860        # node exporter full
        - id: 13679       # mikrotik exporter
