---
- name: Create config and data directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0644
  loop:
    - "{{ reverse_proxy.config_dir }}"

- name: Generate config files
  ansible.builtin.template:
    src: templates/{{ item.src }}
    dest: "{{ reverse_proxy.config_dir }}/{{ item.dest }}"
    mode: 0644
  loop:
    - src: nginx.conf.j2
      dest: nginx.conf
    - src: proxy.conf.j2
      dest: proxy.conf
    - src: index.html.j2
      dest: index.html
