---
- name: Check if config directory is exists
  ansible.builtin.stat:
    path: "{{ reverse_proxy.config_dir }}"
  register: nginx_config_dir_info

- name: Create data directory
  ansible.builtin.file:
    path: "{{ reverse_proxy.config_dir }}"
    state: directory
    mode: 0644
  when: nginx_config_dir_info.stat.exists == false

- name: Generate config files
  ansible.builtin.template:
    src: templates/{{ item.src }}
    dest: "{{ config_dir }}/{{ item.dest }}"
    mode: 0644
  loop:
    - src: nginx.conf.j2
      dest: nginx.conf
    - src: proxy.conf.j2
      dest: proxy.conf
    - src: index.html.j2
      dest: index.html
