---
- name: List all virtual hosts
  ansible.builtin.set_fact:
    root_domain: "{{ ritsu.components.reverse_proxy.root_domain }}"
    virtual_hosts:
      # TODO: add more virtual hosts here
      - subdomain: cadvisor
        upstream: exporter_cadvisor:8080
        enabled: "{{ ritsu.components.exporter_cadvisor.enabled | default(false) }}"
      - subdomain: grafana
        upstream: grafana:3000
        enabled: "{{ ritsu.components.grafana.enabled | default(false) }}"

- name: Create config and data directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "{{ ritsu.config_dir }}/nginx"
    - "{{ ritsu.config_dir }}/nginx/ssl"
    - "{{ ritsu.config_dir }}/nginx/sites"

- name: Generate index page and base route config
  ansible.builtin.template:
    src: templates/{{ item.src }}
    dest: "{{ ritsu.config_dir }}/nginx/{{ item.dest }}"
    mode: "0775"
  loop:
    - src: proxy.conf.j2
      dest: proxy.conf
    - src: index.html.j2
      dest: index.html
    - src: nginx.conf.j2
      dest: nginx.conf
    - src: site-home.conf.j2
      dest: sites/home.conf
  notify: Restart Nginx

- name: Generate site reverse proxy entries
  ansible.builtin.template:
    src: templates/site.conf.j2
    dest: "{{ ritsu.config_dir }}/nginx/sites/{{ item.subdomain }}.conf"
    mode: "0775"
  when: item.enabled
  loop: "{{ virtual_hosts }}"
  notify: Restart Nginx
