---
- name: Create config and data directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "{{ ritsu.config_dir }}/nginx"

- name: Generate config files
  ansible.builtin.template:
    src: templates/{{ item.src }}
    dest: "{{ ritsu.config_dir }}/nginx/{{ item.dest }}"
    mode: "0775"
  loop:
    - src: nginx.conf.j2
      dest: nginx.conf
    - src: proxy.conf.j2
      dest: proxy.conf
    - src: index.html.j2
      dest: index.html
  notify: Restart Nginx
