---
- name: Create configuration
  ansible.builtin.import_tasks: config.yml

- name: Create SSL certificate
  ansible.builtin.import_tasks: ssl.yml

- name: Create and start container
  ansible.builtin.import_tasks: container.yml
