---
- name: Create config directory
  ansible.builtin.file:
    path: "{{ ritsu.config_dir }}/exporter_mikrotik"
    state: directory
    mode: 0775
  register: config_output

- name: Create configuration
  ansible.builtin.template:
    src: templates/{{ item.src }}
    dest: "{{ config_output.path }}/{{ item.dest }}"
    mode: 0775
  notify: restart_exporter_mikrotik
  loop:
    - src: _mktxp.conf.j2
      dest: _mktxp.conf
    - src: mktxp.conf.j2
      dest: mktxp.conf
