---
- name: Pull image from registry
  community.docker.docker_image:
    state: "{{ ritsu.components.exporter_mikrotik.state }}"
    name: "{{ ritsu.components.exporter_mikrotik.image }}"
    source: pull

- name: Start and connect container to network
  community.docker.docker_container:
    state: "{{ 'started' if (ritsu.components.exporter_mikrotik.state == 'present') else 'absent' }}"
    image: "{{ ritsu.components.exporter_mikrotik.image }}"
    name: exporter_mikrotik
    restart_policy: unless-stopped
    exposed_ports:
      - 49090:49090
    published_ports:
      - "{{ ritsu.components.exporter_mikrotik.port }}:49090"
    networks:
      - name: "{{ ritsu.network.name }}"
    volumes:
      - "{{ ritsu.config_dir }}/exporter_mikrotik:/home/mktxp/mktxp:rw"
