---
- name: Pull image from Docker Hub
  community.docker.docker_image:
    name: "{{ exporter_mikrotik.image }}"
    source: pull

- name: Create configuration
  ansible.builtin.template:
    src: templates/qbittorrent-proxt.toml.j2
    dest: "{{ exporter_mikrotik.config_dir }}/mktxp.toml"
    mode: 0644

- name: Start and connect container to main network
  community.docker.docker_container:
    name: exporter_mikrotik
    image: "{{ exporter_mikrotik.image }}"
    state: started
    restart_policy: always
    command:
      - export
    exposed_ports:
      - "{{ exporter_mikrotik.ports }}:49090"
    networks:
      - name: mainnet
    volumes:
      - "{{ exporter_mikrotik.config_dir }}/mktxp.toml:/home/mktxp/mktxp/mktxp.conf:ro"
