---
- name: Pull image from registry
  community.docker.docker_image:
    name: "{{ ritsu.components.exporter_speedtest.image }}"
    source: pull

- name: Start and connect container to network
  community.docker.docker_container:
    state: started
    name: exporter_speedtest
    image: "{{ ritsu.components.exporter_speedtest.image }}"
    restart_policy: unless-stopped
    exposed_ports:
      - 9798:9798
    published_ports:
      - "{{ ritsu.components.exporter_speedtest.port }}:9798"
    networks:
      - name: "{{ ritsu.network.name }}"
