---
- name: Pull image from Docker Hub
  community.docker.docker_image:
    name: "{{ exporter_speedtest.image }}"
    source: pull

- name: Start and connect container to main network
  community.docker.docker_container:
    name: exporter_speedtest
    image: "{{ exporter_speedtest.image }}"
    state: started
    restart_policy: always
    exposed_ports:
      - "{{ exporter_speedtest.port }}:9798"
    networks:
      - name: mainnet
