---
- name: Pull image from registry
  community.docker.docker_image:
    state: "{{ ritsu.components.exporter_speedtest.state }}"
    name: "{{ ritsu.components.exporter_speedtest.image }}"
    source: pull

- name: Start and connect container to network
  community.docker.docker_container:
    state: "{{ 'started' if (ritsu.components.exporter_speedtest.state == 'present') else 'absent' }}"
    image: "{{ ritsu.components.exporter_speedtest.image }}"
    name: exporter_speedtest
    restart_policy: unless-stopped
    exposed_ports:
      - 9798:9798
    published_ports:
      - "{{ ritsu.components.exporter_speedtest.port }}:9798"
    networks:
      - name: "{{ ritsu.network.name }}"
