---
# Mikrotik Exporter
# Exports metrics from Mikrotik routers to Prometheus.
ritsu:
  components:
    exporter_mikrotik:
      image: ghcr.io/akpw/mktxp:stable-20230706091740

      # web UI access
      port: 8103

      # Mikrotik router host
      router:
        host: 10.20.20.1
        port: 8728

      # Mikrotik user with API access
      user:
        username: mktxp
        password: mktxp
