---
# ------------------------------------------------------------------------------
# Mikrotik Exporter
# Exports metrics from Mikrotik devices to Prometheus.
#
# Depends on:
# - prometheus
#   Uses prometheus to collect metrics.
#   If prometheus is disabled, the play will fail.
# - grafana
#   If grafana is enabled, a dashboard will be provisioned.
ritsu:
  components:
    exporter_mikrotik:
      # image to run
      image: ghcr.io/akpw/mktxp:latest

      # metrics port
      port: 8103

      # when using reverse proxy, http://{{subdomain}}.{{global_domain}}
      subdomain: mktxp

      # router config
      router_hostname: 10.20.20.1
      router_api_port: 8728
      router_username: admin
      router_password: admin
