---
# Pi-hole
# Block ads and trackers with optional DNSCrypt integration.
#
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
pihole_state: present

# docker image
pihole_image: pihole/pihole:2023.11.0

# web UI access
pihole_port: 8003
pihole_password: foobar123

# enable DNSCrypt integration
# this config can only be enabled for first time installation
pihole_dnscrypt: false
