---
# Pi-hole
# Block ads and trackers with optional DNSCrypt integration.
#
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
ritsu:
  components:
    pihole:
      state: present
      image: pihole/pihole:2023.11.0

      # web UI access
      port: 8003
      password: foobar123

      # enable DNSCrypt integration
      # this config can only be enabled for first time installation
      dnscrypt: false
