---
# Prometheus
prometheus_state: present

# docker image
prometheus_image: prom/prometheus:v2.48.0

# web UI access
prometheus_port: 8005

# retention
prometheus_retention:
  time: 2y
  size: 100GB

# apps to be monitored
prometheus_exporters:
  node:
    enabled: true
    version: 1.8.2
    arch: linux-armv7
    install_path: /usr/local/bin/node_exporter
    port: 8102
    user_group: node-exporter

  blackbox:
    enabled: true
    state: present
    image: prom/blackbox-exporter:v0.23.0
    port: 8102

  cadvisor:
    enabled: true
    state: present
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    port: 8101

  mikrotik:
    enabled: true
    state: present
    image: ghcr.io/akpw/mktxp:stable-20230706091740
    port: 8103

    # Mikrotik router host
    router:
      host: 10.20.20.1
      port: 8728

    # Mikrotik user with API access
    user:
      username: ""
      password: ""

  speedtest:
    enabled: true
    state: present
    image: miguelndecarvalho/speedtest-exporter:v3.5.4
    port: 8105

    # Configure the sample_interval to limit the number of checks interval because
    # the speed test will consume a considerable amount of bandwidth.
    scrape_interval: 1h
