---
# Prometheus
ritsu:
  components:
    prometheus:
      image: prom/prometheus:v2.48.0

      # web UI access
      port: 8005

      # retention
      retention:
        time: 30d
        size: 10GB
