---
# ------------------------------------------------------------------------------
# Prometheus
# Used to collect metrics from the system and acts as time series database.
ritsu:
  components:
    prometheus:
      image: prom/prometheus:v2.39.1
      port: 8005
