---
- name: Create config directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - "{{ ritsu.config_dir }}/plex/config"

- name: Check if media directory is exists
  ansible.builtin.stat:
    path: "{{ ritsu.components.plex.media_dir }}"
  register: plex_media_dir_exists

- name: Assert media directory exists
  ansible.builtin.assert:
    that:
      - plex_media_dir_exists.stat.exists
      - plex_media_dir_exists.stat.isdir

- name: Assert claim token is not empty
  ansible.builtin.assert:
    that:
      - ritsu.components.plex.claim_token != ""
