---
- name: Pull image from registry
  community.docker.docker_image:
    name: "{{ ritsu.components.plex.image }}"
    source: pull

- name: Start and connect container to network
  community.docker.docker_container:
    state: started
    name: plex
    image: "{{ ritsu.components.plex.image }}"
    restart_policy: unless-stopped
    env:
      TZ: "{{ ritsu.timezone }}"
      VERSION: "docker"
      PLEX_CLAIM: "{{ ritsu.components.plex.claim_token }}"
    published_ports:
      - "{{ ritsu.components.plex.port }}:32400"
    networks:
      - name: "{{ ritsu.network.name }}"
    volumes:
      - "{{ ritsu.config_dir }}/plex:/config"
    devices:
      - /dev/dri:/dev/dri
    mounts:
      - source: "{{ ritsu.components.plex.media_dir }}"
        target: /movies
        type: bind
