---
# Ookla SpeedTest
# Periodically run speed test to measure network performance.
#
# Note:
# Configure the sample_interval to limit the number of checks interval because
# the speed test will consume a considerable amount of bandwidth.
ritsu:
  components:
    exporter_speedtest:
      image: miguelndecarvalho/speedtest-exporter:v3.5.4

      # web UI access
      port: 8105

      # prometheus scrape interval
      # only applied when prometheus component is enabled
      scrape_interval: 1h
