---
# ------------------------------------------------------------------------------
# Ookla SpeedTest
# Periodically run speed test to measure network performance.
#
# Depends on:
# - prometheus
#   Uses prometheus to collect metrics.
#   If prometheus is disabled, the play will fail.
# - grafana
#   If grafana is enabled, a dashboard will be provisioned.
#
# Note:
# Configure the sample_interval to limit the number of checks interval because
# the speed test will consume a considerable amount of bandwidth.
ritsu:
  components:
    exporter_speedtest:
      # docker image to run
      image: miguelndecarvalho/speedtest-exporter:latest

      # metrics port
      port: 8105
      scrape_interval: 1h

      # when using reverse proxy, http://{{subdomain}}.{{global_domain}}
      subdomain: speedtest
