---
- name: Create config directory
  ansible.builtin.file:
    path: "{{ ritsu.config_dir }}/pihole/{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - etc
    - dnsmasq.d

- name: Assert DNSCrypt is enabled if Pi-Hole is using it
  ansible.builtin.assert:
    that:
      - ritsu.components.dnscrypt.enabled
    fail_msg: Before using DNSCrypt with Pi-Hole, DNSCrypt must be enabled
    success_msg: Using Pi-Hole with DNSCrypt integration
  when: ritsu.components.pihole.dnscrypt

- name: Get dnscrypt IP address
  community.docker.docker_container_info:
    name: dnscrypt
  register: pihole_dnscrypt_info
  when: ritsu.components.pihole.dnscrypt
